app:
  name: {{ cookiecutter.app_name }}
  env: prod

  # the app's container resource spec
  resources:
    requests:
      cpu: "50m"
      memory: "32Mi"

  # autoscale configuration
  autoscale:
    enabled: true
    maxReplica: 10
    minReplica: 1
    targetCPUUtilizationPercentage: 60

  # it will configure the configmap named: "<app.name>-<app.track>-envs"
  # by default it already contains ENVIRONMENT=<app.env>
  configmap:
    data:
      SERVICE_OWNER: {{ cookiecutter.owner }}

infra:
  virtualService:
    # all request from this host will follow routing rules
    hosts:
    - raring-meerkat.tvlk-data.com
    # istio ingress gateway
    gateway: 
    - raring-meerkat-gateway

  trafficRoute:
    blacklist:
      enabled: false
    timeout: 15s
    retries:
      attempts: 3
      perTryTimeout: 1s
    weight:
      stable: 100
      canary: 0