---
swagger: "2.0"
info:
  title: {{ cookiecutter.app_name }}-stg
  description: "Staging service created by Raring Meerkat Platform"
  version: "2.0.0"
host: "{{ cookiecutter.app_name }}-stg.endpoints.tvlk-data-mlplatform-prod.cloud.goog"
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
  - "http"
paths:
  /info:
    get:
      description: "Return information about the service"
      summary: ""
      operationId: "info"
      produces:
        - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Common200"
        500:
          $ref: '#/responses/InternalServerError'
        default:
          $ref: '#/responses/UnknownError'
  /health:
    get:
      description: "Return whether the service is healthy or not"
      summary: ""
      operationId: "health"
      produces:
        - "application/json"
      responses:
        200:
          description: OK
        500:
          $ref: '#/responses/InternalServerError'
  /status:
    get:
      description: "Return whether the service is ready"
      summary: ""
      operationId: "status"
      produces:
        - "application/json"
      responses:
        200:
          description: OK
        500:
          $ref: '#/responses/InternalServerError'
  /predict:
    post:
      description: "Return prediction from the service"
      summary: ""
      operationId: "predict"
      produces:
        - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Common200"
        500:
          $ref: '#/responses/InternalServerError'
        default:
          $ref: '#/responses/UnknownError'
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
definitions:
  Common200:
      type: "object"
      properties:
        status_code:
          type: integer
        data:
          type: object
responses:
  InternalServerError:
    description: Internal server error.
  UnknownError:
    description: Unknown error.
